[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  PUBLIC_URL = "https://imagenerator.netlify.app"
  REACT_APP_BASE_URL = "https://imagenerator.netlify.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200